version: '3.8'
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: '${CONTAINER_NAME}'
    ports:
      - '${HOST_PORT}:4200'
    env_file:
        - .env
    networks:
      docker_network: null


networks:
  docker_network:
    external: true
